{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4e586cc1",
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "import requests\n",
    "import re\n",
    "import time\n",
    "from time import sleep\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from bs4 import BeautifulSoup as bs\n",
    "import pandas as pd\n",
    "import os\n",
    "from datetime import datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f7f9f6aa",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "number of Scrped reviews :  10\n",
      "number of Scrped reviews :  20\n",
      "number of Scrped reviews :  30\n",
      "number of Scrped reviews :  40\n",
      "number of Scrped reviews :  50\n",
      "number of Scrped reviews :  60\n",
      "number of Scrped reviews :  70\n",
      "number of Scrped reviews :  80\n",
      "number of Scrped reviews :  90\n",
      "number of Scrped reviews :  100\n",
      "number of Scrped reviews :  110\n",
      "number of Scrped reviews :  120\n",
      "number of Scrped reviews :  130\n",
      "number of Scrped reviews :  140\n",
      "number of Scrped reviews :  150\n",
      "number of Scrped reviews :  160\n",
      "number of Scrped reviews :  170\n",
      "number of Scrped reviews :  180\n",
      "number of Scrped reviews :  190\n",
      "number of Scrped reviews :  200\n",
      "number of Scrped reviews :  210\n",
      "number of Scrped reviews :  220\n",
      "number of Scrped reviews :  230\n",
      "number of Scrped reviews :  240\n",
      "number of Scrped reviews :  250\n",
      "number of Scrped reviews :  260\n",
      "number of Scrped reviews :  270\n",
      "number of Scrped reviews :  280\n",
      "number of Scrped reviews :  290\n",
      "number of Scrped reviews :  300\n",
      "소요시간 : 125 2\n"
     ]
    }
   ],
   "source": [
    "driver = webdriver.Chrome()\n",
    "\n",
    "titles = [] # 타이틀\n",
    "stars = [] # 별점\n",
    "dates = [] # 날짜\n",
    "contents = [] # 컨텐츠\n",
    "    \n",
    "url1 = \"https://www.amazon.co.uk/Bosch-WAN282X1GB-Freestanding-AllergyPlus-SpeedPerfect/product-reviews/B08P7WMCQX/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=\"\n",
    "url0 = 0 # 페이지 변경\n",
    "\n",
    "start_time = time.time()\n",
    "\n",
    "for url2 in range(1,31):\n",
    "    url = url1 + str(url2)\n",
    "    driver.get(url)\n",
    "    driver.implicitly_wait(10) # wait time\n",
    "    res = driver.page_source\n",
    "    obj = bs(res,'html.parser')\n",
    "\n",
    "    source = driver.page_source\n",
    "    \n",
    "    bs_obj = bs(source, \"html.parser\")\n",
    "\n",
    "    for i in bs_obj.findAll('a',{'data-hook':'review-title'}):\n",
    "        titles.append(i.get_text().strip())\n",
    "        \n",
    "    for n in bs_obj.findAll('span',{'data-hook':'review-date'}):\n",
    "        nn = ''.join(n.get_text().split(' ')[-3:])\n",
    "        date = datetime.strptime(nn, '%d%B%Y').date()\n",
    "        dates.append(date)\n",
    "        \n",
    "    for a in bs_obj.findAll('span',{'data-hook':'review-body'}):\n",
    "        contents.append(a.get_text().strip())\n",
    "        \n",
    "    for u in bs_obj.findAll('i', {'data-hook':'review-star-rating'}):\n",
    "        stars.append(int(u.get_text()[0]))\n",
    "        \n",
    "    print('number of Scrped reviews : ', len(titles))\n",
    "\n",
    "end_time = time.time()\n",
    "\n",
    "df2 = pd.DataFrame({'Dates':dates,'Ratings':stars, \"Titles\":titles, \"Bodys\":contents})\n",
    "\n",
    "print(\"소요시간 : {0}\".format(round(end_time - start_time)), 2)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "516a5cd3",
   "metadata": {},
   "source": [
    "## 데이터 정보 확인"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "acc2e13b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Dates</th>\n",
       "      <th>Ratings</th>\n",
       "      <th>Titles</th>\n",
       "      <th>Bodys</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2023-04-30</td>\n",
       "      <td>4</td>\n",
       "      <td>Stunning!!!</td>\n",
       "      <td>Video Player is loading.Play VideoPlayMuteCurr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2023-04-17</td>\n",
       "      <td>4</td>\n",
       "      <td>Short hoses</td>\n",
       "      <td>Machine is good but water inlet hose and drain...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2023-04-17</td>\n",
       "      <td>5</td>\n",
       "      <td>that it was as good as my previous bosh washin...</td>\n",
       "      <td>brill</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2023-01-22</td>\n",
       "      <td>4</td>\n",
       "      <td>Would recommend buying this.</td>\n",
       "      <td>This is the most expensive washing machine I’v...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2023-03-30</td>\n",
       "      <td>5</td>\n",
       "      <td>Excellent Product.</td>\n",
       "      <td>Very good Machine ,price is excellent &amp; very e...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>295</th>\n",
       "      <td>2021-02-28</td>\n",
       "      <td>5</td>\n",
       "      <td>So quiet!</td>\n",
       "      <td>Upgraded from my 5 year old Bosch and glad I d...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>296</th>\n",
       "      <td>2021-06-26</td>\n",
       "      <td>5</td>\n",
       "      <td>So, so quiet</td>\n",
       "      <td>I had to look to make sure the washing machine...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>297</th>\n",
       "      <td>2021-02-16</td>\n",
       "      <td>5</td>\n",
       "      <td>Good washer</td>\n",
       "      <td>Does the job A+++</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>298</th>\n",
       "      <td>2021-10-13</td>\n",
       "      <td>4</td>\n",
       "      <td>IT LOOKS GREAT BUT NO INSTALLATION PROVIDED</td>\n",
       "      <td>It seems to be as advertised, but what was ver...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>299</th>\n",
       "      <td>2021-03-01</td>\n",
       "      <td>5</td>\n",
       "      <td>For the price very good</td>\n",
       "      <td>Nice wash machine very quiet  Very happy with it</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>300 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          Dates  Ratings                                             Titles  \\\n",
       "0    2023-04-30        4                                        Stunning!!!   \n",
       "1    2023-04-17        4                                        Short hoses   \n",
       "2    2023-04-17        5  that it was as good as my previous bosh washin...   \n",
       "3    2023-01-22        4                       Would recommend buying this.   \n",
       "4    2023-03-30        5                                 Excellent Product.   \n",
       "..          ...      ...                                                ...   \n",
       "295  2021-02-28        5                                          So quiet!   \n",
       "296  2021-06-26        5                                       So, so quiet   \n",
       "297  2021-02-16        5                                        Good washer   \n",
       "298  2021-10-13        4        IT LOOKS GREAT BUT NO INSTALLATION PROVIDED   \n",
       "299  2021-03-01        5                            For the price very good   \n",
       "\n",
       "                                                 Bodys  \n",
       "0    Video Player is loading.Play VideoPlayMuteCurr...  \n",
       "1    Machine is good but water inlet hose and drain...  \n",
       "2                                                brill  \n",
       "3    This is the most expensive washing machine I’v...  \n",
       "4    Very good Machine ,price is excellent & very e...  \n",
       "..                                                 ...  \n",
       "295  Upgraded from my 5 year old Bosch and glad I d...  \n",
       "296  I had to look to make sure the washing machine...  \n",
       "297                                  Does the job A+++  \n",
       "298  It seems to be as advertised, but what was ver...  \n",
       "299   Nice wash machine very quiet  Very happy with it  \n",
       "\n",
       "[300 rows x 4 columns]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a2b00510",
   "metadata": {},
   "source": [
    "## 데이터 저장"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c9691b5e",
   "metadata": {},
   "outputs": [],
   "source": [
    "df2.to_csv('amazon_WAN282X1GB.csv')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
