{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "bb8b3926",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "import nltk\n",
    "import fitz\n",
    "import re\n",
    "import copy\n",
    "import pprint\n",
    "import warnings\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import image\n",
    "import pytesseract\n",
    "\n",
    "from PIL import Image\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.stem import WordNetLemmatizer\n",
    "from gensim.corpora.dictionary import Dictionary\n",
    "from gensim import corpora\n",
    "from tqdm import tqdm"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d7399866",
   "metadata": {},
   "source": [
    "## 크롤링 텍스트 데이터 전처리 반환 함수"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ad52e228",
   "metadata": {},
   "outputs": [],
   "source": [
    "def clean_text(texts): \n",
    "    corpus = []\n",
    "    \n",
    "    for i in tqdm(range(0, len(texts))):\n",
    "        \n",
    "        body = texts[i]\n",
    "        \n",
    "        body = re.sub('[^a-zA-Z]', ' ', body) # 특수문자 제거 \n",
    "        body = body.lower().split() # 대문자를 소문자로 변경, 문장을 단어 단위로 구분\n",
    "        \n",
    "        df['clean_text'][i] = body\n",
    "        \n",
    "        stops = stopwords.words('english')\n",
    "        stops.append('machine')\n",
    "        stops.append('product')\n",
    "        stops.append('bosch')\n",
    "        \n",
    "        no_stops = [word for word in body if not word in stops] # 불용어 제거\n",
    "        df['stopwords_after'][i] = no_stops\n",
    "        \n",
    "        tokens_pos = nltk.pos_tag(df['stopwords_after'][i]) # pos tagging (품사 태깅)\n",
    "        df['pos_tag'][i] = tokens_pos\n",
    "        \n",
    "        NN_words = [] # 명사만 추출\n",
    "        for word, pos in tokens_pos:\n",
    "            if 'NN' in pos:\n",
    "                NN_words.append(word)\n",
    "                df['NN'][i] = NN_words\n",
    "                \n",
    "        wlem = nltk.WordNetLemmatizer() # Lemmatization(원형(lemma) 찾기) # nltk에서 제공되는 WordNetLemmatizer을 이용\n",
    "        lemmatized_words = []\n",
    "        \n",
    "        for word in NN_words:\n",
    "            new_word = wlem.lemmatize(word)\n",
    "            lemmatized_words.append(new_word)\n",
    "            df['lemmatization'][i] = lemmatized_words\n",
    "        \n",
    "        corpus.append(no_stops) \n",
    "        \n",
    "    return corpus"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c936b4eb",
   "metadata": {},
   "source": [
    "## 목차 리스트 반환 함수"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "6c4a88ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "def contents_exteaction(list1):\n",
    "    \n",
    "    pattern = re.compile(\"n\\d{1,2}\\s{1}[A-Z][a-z\\t\\n\\r\\f\\v\\s]+[a-z\\t\\n\\r\\f\\v\\s]+\\W[a-z\\t\\n\\r\\f\\v\\s]*\")\n",
    "    contents = pattern.findall(str(document))[:-6]\n",
    "\n",
    "    for idx, st in enumerate(contents):\n",
    "        contents[idx] = re.sub(\"n[0-9]{1,2}[\\s]\", \"\", contents[idx])\n",
    "        contents[idx] = contents[idx].replace(\"\\\\n\", \" \").replace(\".\", \"\").strip()\n",
    "        \n",
    "    return contents, len(contents)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cf4430cc",
   "metadata": {},
   "source": [
    "## 목차 리스트 리뷰 검색이 가능한 키워드 리스트 반환 함수"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e39e706e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def contents_review_search(document):\n",
    "    \n",
    "    stops = stopwords.words('english') # 라이브러리에서 제공하는 불용어 \n",
    "    stops_plus = ['tion', 'ance', 'tem', 'con', 'machine', 'product', 'bosch', 'ines', \n",
    "                  'page', 'Start','bosch', 'www', 'zips', 'tions', 'wmzpw', 'wmz'] # 사용자 지정 불용어 설정\n",
    "    \n",
    "    pattern = re.compile(\"n\\d{1,2}\\s{1}[A-Z][a-z\\t\\n\\r\\f\\v\\s]+[a-z\\t\\n\\r\\f\\v\\s]+\\W[a-z\\t\\n\\r\\f\\v\\s]*\")\n",
    "    contents = pattern.findall(str(document))[:-6]\n",
    "\n",
    "    for idx, st in enumerate(contents):\n",
    "        contents[idx] = re.sub(\"n[0-9]{1,2}[\\s]\", \"\", contents[idx])\n",
    "        contents[idx] = contents[idx].replace(\"\\\\n\", \" \").replace(\".\", \"\").strip()\n",
    "    \n",
    "    contents_word = []\n",
    "\n",
    "    for word in contents:\n",
    "        contents_word.append(word.lower().split(' '))\n",
    "\n",
    "    contents_word = sum(contents_word, [])\n",
    "\n",
    "    contents_word = list(set(contents_word))\n",
    "\n",
    "    lem = nltk.WordNetLemmatizer()\n",
    "    contents_word_lemma = [lem.lemmatize(word) for word in contents_word]\n",
    "\n",
    "    contents_word_re = [word for word in contents_word if (not word in stops)]\n",
    "\n",
    "\n",
    "    possible_keyword = []\n",
    "\n",
    "    for idx1, st1 in enumerate(df['lemmatization']):\n",
    "        for idx2, st2 in enumerate(st1):\n",
    "            if st2 in contents_word_re:\n",
    "                possible_keyword.append(st2)\n",
    "            else:\n",
    "                continue\n",
    "\n",
    "    return sorted(list(set(possible_keyword)))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0fd8c6e2",
   "metadata": {},
   "source": [
    "## WAN282X1GB Amazon review data keyword frequency"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ca8aa556",
   "metadata": {},
   "outputs": [],
   "source": [
    "def Crawling_Text_Data_Keyword_Frequecy(list1):\n",
    "    \n",
    "    list1_cp = copy.deepcopy(list1) # 데이터 복사본 생성\n",
    "    \n",
    "    count = 0\n",
    "    \n",
    "    for idx1, st1 in enumerate(list1_cp['lemmatization']):\n",
    "        for idx2, st2 in enumerate(st1):\n",
    "            if len(st2) <= 2:\n",
    "                count += 1\n",
    "            else:\n",
    "                continue\n",
    "                \n",
    "                \n",
    "    dictionary = corpora.Dictionary(list1_cp['lemmatization'])\n",
    "    corpus = [dictionary.doc2bow(text) for text in list1_cp['lemmatization']]\n",
    "    \n",
    "    df_lemma = []\n",
    "\n",
    "    for idx1, st1 in enumerate(list1_cp['lemmatization']):\n",
    "        for idx2, st2 in enumerate(st1):\n",
    "            df_lemma.append(st2)\n",
    "            \n",
    "    wordcount2 = {}\n",
    "\n",
    "    for word in df_lemma:\n",
    "\n",
    "        wordcount2[word] = wordcount2.get(word, 0) + 1\n",
    "        keys = sorted(wordcount2.keys())\n",
    "        \n",
    "    dict_count2 = {}\n",
    "\n",
    "    for word in keys:\n",
    "        dict_count2[word] = [wordcount2[word]]\n",
    "        \n",
    "    df_count2 = pd.DataFrame(dict_count2)\n",
    "    \n",
    "    df_count2 = df_count2.T\n",
    "    df_count2.rename(columns = {0 : 'Frequency'}, inplace = True)\n",
    "    df_count2.sort_values('Frequency', ascending = False)\n",
    "    review_text_keyword_frequency = df_count2.sort_values('Frequency', ascending = False)\n",
    "    review_text_keyword_frequency['Portion'] = round(100 * (review_text_keyword_frequency / review_text_keyword_frequency.sum()), 2)\n",
    "    \n",
    "    return review_text_keyword_frequency"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5e16e4e9",
   "metadata": {},
   "source": [
    "## WAN282X1GB Manual Keyword Frequency"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "0d11844f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def Manual_Keyword_Frequency(list2):\n",
    "    \n",
    "    # Data copy\n",
    "    sentence = copy.deepcopy(list2)\n",
    "    \n",
    "    # Preprocessing\n",
    "    for idx, st in enumerate(sentence):\n",
    "        sentence[idx] = re.sub(r\"[^a-zA-Z0-9]\", \" \", sentence[idx])\n",
    "        sentence[idx] = re.sub(r\"[0-9]\", \" \", sentence[idx])\n",
    "        sentence[idx] = re.sub(' +', ' ', sentence[idx])\n",
    "        sentence[idx] = nltk.word_tokenize(sentence[idx])\n",
    "    \n",
    "    sentence_1d = sum(sentence, [])\n",
    "    stops = stopwords.words('english') # 라이브러리에서 제공하는 불용어 \n",
    "    stops_plus = ['tion', 'ance', 'tem', 'con', 'machine', 'product', 'bosch', 'ines', \n",
    "                  'page', 'Start','bosch', 'www', 'zips', 'tions', 'wmzpw', 'wmz'] # 사용자 지정 불용어 설정\n",
    "\n",
    "    for i in range(len(stops_plus)): # 라이브러리에서 제공하는 불용어에 사용자 지정 불용어를 추가함\n",
    "        stops.append(stops_plus[i])\n",
    "        \n",
    "    clean_sentence_1d = [word for word in sentence_1d if (len(word) > 2) & (not(word in stops))]\n",
    "    \n",
    "    # 품사 태깅\n",
    "    tokens_postag = nltk.pos_tag(clean_sentence_1d)\n",
    "    \n",
    "    # Noun Extraction\n",
    "    NN_words = []\n",
    "    for word, pos in tokens_postag:\n",
    "        \n",
    "        if ('NN' in pos):\n",
    "            NN_words.append(word)\n",
    "        else:\n",
    "            continue\n",
    "    \n",
    "    # Lemmatization Extraction\n",
    "    lemma_collection = []\n",
    "    lemmatizer = WordNetLemmatizer()\n",
    "\n",
    "    for word in NN_words:\n",
    "        \n",
    "        lemma_collection.append(lemmatizer.lemmatize(word))\n",
    "    \n",
    "    lemma_collection_pre = [word for word in sentence_1d if (len(word) > 2) & (not(word in stops))]\n",
    "    \n",
    "    word_count = {}\n",
    "    dict_count = {}\n",
    "    \n",
    "    for word in lemma_collection_pre:\n",
    "        \n",
    "        word_count[word] = word_count.get(word, 0) + 1\n",
    "        keys = sorted(word_count.keys())\n",
    "        \n",
    "    for word in keys:\n",
    "        \n",
    "        dict_count[word] = [word_count[word]]\n",
    "        \n",
    "    df_count = pd.DataFrame(dict_count)\n",
    "    df_count = df_count.T\n",
    "    df_count.rename(columns = {0 : 'Frequency'}, inplace = True)\n",
    "    key_word_frequency = df_count.sort_values('Frequency', ascending = False)\n",
    "    key_word_frequency['Portion'] = round(100 * (key_word_frequency / key_word_frequency.sum()),2)\n",
    "    \n",
    "    return key_word_frequency"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "867cc33d",
   "metadata": {},
   "source": [
    "## Manual Keyword Search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d6b705ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "def Manual_Keyword_Search(list2):\n",
    "    \n",
    "    # Data copy\n",
    "    sentence = copy.deepcopy(list2)\n",
    "    \n",
    "    # Preprocessing\n",
    "    for idx, st in enumerate(sentence):\n",
    "        sentence[idx] = re.sub(r\"[^a-zA-Z0-9]\", \" \", sentence[idx])\n",
    "        sentence[idx] = re.sub(r\"[0-9]\", \" \", sentence[idx])\n",
    "        sentence[idx] = re.sub(' +', ' ', sentence[idx])\n",
    "        sentence[idx] = nltk.word_tokenize(sentence[idx])\n",
    "    \n",
    "    sentence_1d = sum(sentence, [])\n",
    "    stops = stopwords.words('english') # 라이브러리에서 제공하는 불용어 \n",
    "    stops_plus = ['tion', 'ance', 'tem', 'con', 'machine', 'product', 'bosch', 'ines', \n",
    "                  'page', 'Start','bosch', 'www', 'zips', 'tions', 'wmzpw', 'wmz'] # 사용자 지정 불용어 설정\n",
    "    \n",
    "    for i in range(len(stops_plus)): # 라이브러리에서 제공하는 불용어에 사용자 지정 불용어를 추가함\n",
    "        stops.append(stops_plus[i])\n",
    "    \n",
    "    # 품사 태깅\n",
    "    tokens_postag = nltk.pos_tag(sentence_1d)\n",
    "    \n",
    "    # Noun Extraction\n",
    "    NN_words = []\n",
    "    for word, pos in tokens_postag:\n",
    "        \n",
    "        if ('NN' in pos):\n",
    "            NN_words.append(word)\n",
    "        else:\n",
    "            continue\n",
    "    \n",
    "    # Lemmatization Extraction\n",
    "    lemma_collection = []\n",
    "    lemmatizer = WordNetLemmatizer()\n",
    "\n",
    "    for word in NN_words:\n",
    "        \n",
    "        lemma_collection.append(lemmatizer.lemmatize(word))\n",
    "    \n",
    "    lemma_collection_lw = [word.lower() for word in sentence_1d]\n",
    "    \n",
    "    lemma_collection_pre = [word for word in lemma_collection_lw if (len(word) > 2) & (not word in stops)]\n",
    "    \n",
    "    word_coll = []\n",
    "    \n",
    "    for idx1, st1 in enumerate(df['lemmatization']):\n",
    "        for idx2, st2 in enumerate(st1):\n",
    "            if st2 in lemma_collection_pre:\n",
    "                word_coll.append(st2)\n",
    "            else:\n",
    "                continue\n",
    "            \n",
    "    # lemma_collection_pre = sorted(list(set(lemma_collection_pre))) \n",
    "    \n",
    "    return(list(set(word_coll)))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fcf4fbf9",
   "metadata": {},
   "source": [
    "## Manual Keyword Search - manual, review 별 빈도"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "21061ca5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def Manual_Keyword_Search_Score(list2):\n",
    "    word_col = Manual_Keyword_Search(document)\n",
    "    df1_cr = Crawling_Text_Data_Keyword_Frequecy(df)\n",
    "    df2_mn = Manual_Keyword_Frequency(document)\n",
    "    \n",
    "    dict_word_col = {}\n",
    "    list1 = []\n",
    "    for idx1, st1 in enumerate(word_col):\n",
    "        for idx2, st2 in enumerate(df1_cr.index):\n",
    "            if st1 == st2:\n",
    "                for idx3, st3 in enumerate(df2_mn.index):\n",
    "                    if st1 == st3:\n",
    "                        dict_word_col = {st1 : idx1, 'manual_freq' : df2_mn[df2_mn.index == st1]['Frequency'][0],\n",
    "                                        'review_freq' : df1_cr[df1_cr.index == st1]['Frequency'][0]}\n",
    "                        list1.append(dict_word_col)\n",
    "\n",
    "                    else:\n",
    "                        continue\n",
    "            else:\n",
    "                continue\n",
    "                \n",
    "    new_dict = {}\n",
    "    dict_word, dict_mn_freq, dict_cr_freq = [], [], []\n",
    "\n",
    "    for i in range(0, len(list1)):\n",
    "        dict_word.append(list(list1[i].keys())[0])\n",
    "        dict_mn_freq.append(list(list1[i].values())[1])\n",
    "        dict_cr_freq.append(list(list1[i].values())[2])\n",
    "\n",
    "\n",
    "    new_dict = {\"word\" : dict_word, \"manual_freq\" : dict_mn_freq, \"review_freq\" : dict_cr_freq}\n",
    "    df_new_dict = pd.DataFrame(new_dict)\n",
    "    \n",
    "    return df_new_dict.sort_values(by = 'word')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1acdb071",
   "metadata": {},
   "source": [
    "## Crwaling 데이터 평점 시각화"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c024323d",
   "metadata": {},
   "outputs": [],
   "source": [
    "def Crwaling_data_score_vis(keyword):\n",
    "    search_keyword = Manual_Keyword_Search(document)\n",
    "    date, title, review, star = [], [], [], []\n",
    "    \n",
    "    for idx, st in enumerate(df['lemmatization']):\n",
    "\n",
    "        if keyword in st:\n",
    "            date.append(df['Date'][idx])\n",
    "            title.append(df['Title'][idx])\n",
    "            review.append(df['Body'][idx])\n",
    "            star.append(df['Star'][idx])\n",
    "\n",
    "        else:\n",
    "            continue\n",
    "            \n",
    "    review_collection = pd.DataFrame({'date' : date, 'title' : title, 'review' : review, 'star' : star})\n",
    "    collection = review_collection.sort_values('date')\n",
    "    collection_score = collection['star'].value_counts().to_frame('score')\n",
    "    collection_score['portion'] = round(collection_score['score'] / collection_score['score'].sum(), 2)\n",
    "    wedgeprops={'width': 0.7, 'edgecolor': 'w', 'linewidth': 5}\n",
    "    plt.pie(collection_score['portion'], labels = collection_score.index, autopct='%.1f%%', startangle=260, counterclock=False, wedgeprops=wedgeprops)\n",
    "\n",
    "    return plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eb804dfe",
   "metadata": {},
   "source": [
    "## Review All Search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "f8e4c47a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def Review_All_Search(Keyword):\n",
    "    \n",
    "    title, sentence, date, star = [], [], [], []\n",
    "\n",
    "    for idx1, st1 in enumerate(df['lemmatization']):\n",
    "        if Keyword in st1:\n",
    "            title.append(df['Title'][idx1])\n",
    "            sentence.append(df['Body'][idx1])\n",
    "            date.append(df['Date'][idx1])\n",
    "            star.append(df['Star'][idx1])\n",
    "        else:\n",
    "            continue\n",
    "    \n",
    "    return title, sentence, date, star, len(date)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f8f5385f",
   "metadata": {},
   "source": [
    "## Image extraction text <-> review"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "13740672",
   "metadata": {},
   "outputs": [],
   "source": [
    "def Image_compare_review():\n",
    "    \n",
    "    results = []\n",
    "    path = os.getcwd() # get a current file path\n",
    "    file_list = os.listdir(path) # pull the file list from 'path' folder\n",
    "    file_list_py = [file for file in file_list if file.endswith('.png') or file.endswith('jpeg')]\n",
    "    \n",
    "    for path in file_list_py:\n",
    "        image = Image.open(path)\n",
    "        result = pytesseract.image_to_string(image, lang='eng') # bosch don need kor\n",
    "        arr = result.split('\\n') \n",
    "        result = '\\n'.join(arr)\n",
    "        results.append(result)\n",
    "        \n",
    "    for idx, st in enumerate(results):\n",
    "        results[idx] = re.sub(r\"[^a-zA-Z0-9]\", \" \", results[idx])\n",
    "        results[idx] = re.sub(r\"[0-9]\", \" \", results[idx])\n",
    "        results[idx] = re.sub(' +', ' ', results[idx])\n",
    "        results[idx] = nltk.word_tokenize(results[idx])    \n",
    "    \n",
    "    key_word_results = []\n",
    "\n",
    "    for word in results:\n",
    "        if len(word) != 0:\n",
    "            for idx, st in enumerate(word):\n",
    "                key_word_results.append(st.lower())\n",
    "        else:\n",
    "            continue\n",
    "    \n",
    "    key_word_results = list(set(key_word_results))\n",
    "    \n",
    "    key_word_results = [word for word in key_word_results if len(word) > 2]\n",
    "    \n",
    "    count = 0\n",
    "\n",
    "    for idx1, st1 in enumerate(df['lemmatization']):\n",
    "        for idx2, st2 in enumerate(st1):\n",
    "            if st2 in key_word_results:\n",
    "                count += 1\n",
    "            else:\n",
    "                continue\n",
    "        \n",
    "    return key_word_results, count"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "e7003a8b",
   "metadata": {},
   "outputs": [],
   "source": [
    "path = \"user_manual_WAN282X1GB.pdf\"\n",
    "doc = fitz.open(path)\n",
    "document = [] # contents + sentence 정보를 모두 포함\n",
    "\n",
    "for page in doc:\n",
    "    text = page.get_text()\n",
    "    document.append(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "2b636d0d",
   "metadata": {},
   "outputs": [],
   "source": [
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "1316eb92",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('amazon_WAN282X1GB.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "af32dd4e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|███████████████████████████████████████████████████████████████████████████████| 300/300 [00:02<00:00, 112.78it/s]\n"
     ]
    }
   ],
   "source": [
    "df.drop(['Unnamed: 0'], axis = 1, inplace = True)\n",
    "df.columns = ['Date', 'Star', 'Title', 'Body']\n",
    "\n",
    "df['clean_text'] = pd.Series(dtype='object')\n",
    "df['stopwords_after'] = pd.Series(dtype='object')\n",
    "df['pos_tag'] = pd.Series(dtype='object')\n",
    "df['NN'] = pd.Series(dtype='object')\n",
    "df['lemmatization'] = pd.Series(dtype='object')\n",
    "    \n",
    "clean_text(df['Body'])\n",
    "    \n",
    "df.dropna(inplace = True, axis = 0) # 결측치 제거\n",
    "df.reset_index(inplace = True) # 인덱스 초기화"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d23b2df",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "번호를 입력하세요.\n",
      "\n",
      "1. WAN282X1GB Manual Keyword Frequency\n",
      "2. WAN282X1GB Manual Contents Keyword Set Review or Score\n",
      "3. WAN282X1GB Amazon Review Keyword Frequency\n",
      "4. WAN282X1GB Amazon Review or Score\n",
      "5. WAN282X1GB Manual Image Extraction\n",
      "6. Exit\n",
      "\n",
      "2\n",
      "\n",
      "        1. Manual Contents Search(목차 리스트만 출력)\n",
      "        2. Manual Contents Review search(목차와 매칭되는 리뷰 검색)\n",
      "        1\n",
      "\n",
      "총 21개의 목차가 검색되었습니다.\n",
      "================================================================================\n",
      "['Safety', 'Preventing material damage', 'Environmental protection and saving energy', 'Installation and connection', 'Familiarising yourself with your appliance', 'Before using for the first time', 'Display', 'Buttons', 'Programmes', 'Accessories', 'Laundry', 'Detergents and care products', 'Basic operation', 'Childproof lock', 'Basic settings', 'Cleaning and servicing', 'Troubleshooting', 'Transportation, storage and', 'Customer', 'Consumption values', 'Technical data']\n",
      "\n",
      "\n",
      "번호를 입력하세요.\n",
      "\n",
      "1. WAN282X1GB Manual Keyword Frequency\n",
      "2. WAN282X1GB Manual Contents Keyword Set Review or Score\n",
      "3. WAN282X1GB Amazon Review Keyword Frequency\n",
      "4. WAN282X1GB Amazon Review or Score\n",
      "5. WAN282X1GB Manual Image Extraction\n",
      "6. Exit\n",
      "\n",
      "2\n",
      "\n",
      "        1. Manual Contents Search(목차 리스트만 출력)\n",
      "        2. Manual Contents Review search(목차와 매칭되는 리뷰 검색)\n",
      "        2\n",
      "\n",
      "추출된 목차 키워드 중 검색 가능한 키워드 목록\n",
      "--------------------------------------------------------------------------------\n",
      "['appliance', 'care', 'cleaning', 'connection', 'consumption', 'customer', 'damage', 'display', 'energy', 'installation', 'laundry', 'lock', 'material', 'operation', 'protection', 'time']\n",
      "조회할 키워드를 입력하세요. : operation\n",
      "\n",
      "        \n",
      "        1. 리뷰 검색\n",
      "        2. 평점 검색\n",
      "        \n",
      "        2\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYUAAAGFCAYAAAASI+9IAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/OQEPoAAAACXBIWXMAAA9hAAAPYQGoP6dpAAA1GElEQVR4nO3dd3hUZf4F8DM1k8yk90ASEhIChN6b9KKwCDYUsYBdYS27lnWLZe27+3Mta1tW0bUhq2AHFBQUaaGGQGiBkEp6r5OZ+f0xMIImAwkz895yPs/DgzBh5kTCnNz73vt+NQ6HwwEiIiIAWtEBiIhIOlgKRETkwlIgIiIXlgIREbmwFIiIyIWlQERELiwFIiJyYSkQEZELS4GIiFxYCkRE5MJSICIiF5YCERG5sBSIiMiFpUBERC4sBSIicmEpEBGRC0uBiIhcWApEROTCUiAiIheWAhERubAUiIjIhaVAREQuLAUiInJhKRARkQtLgYiIXFgKRETkwlIgIiIXlgIREbmwFIiIyIWlQERELiwFIiJyYSkQEZELS4GIiFxYCkRE5MJSICIiF5YCERG5sBSIiMiFpUBERC4sBSIicmEpEBGRC0uBiIhcWApEROTCUiAiIheWAhERubAUiIjIhaVAREQuLAUiInJhKRARkYtedAAiX2pqtaHZaoPN4YDD4YDdAdhP/exwOGC3O3+t0QBmPz0CTXr46XWiYxP5DEuBZK+0thm5FY3Ir2xEeX0LapqsqGpsRXWjFdWNP/93VWMrWtrsnX5+P70WgSY9Ak2GUz///N+RFj90Dw1A91B/dA/1R7dQf5YIyZrG4XA4RIcgOpeCqkacqGjEiYoG5Fb8/N95lY1obLWJjuei0QARFj/Eh/q7yiIhPAC9owORFhMEfyMLg6SNpUCSU1zThMyCGuzNr0ZmQQ0yC6tR29QmOtYF02qAxHAzescEIj0uGAO6B6N/t2CEmo2ioxG5sBRIqNpmK3afqMLeghpkFlRjb0ENyupaRMfyqe6h/hjYPQQjk8MwtmcEekZZREciFWMpkE/Z7Q7sLajGD4fL8MORcuzJr4bNzi/BM8UEmTAmJRxjUyIwtmcEYoJNoiORirAUyOuKa5rww+Fy/HC4DJuOlqOmySo6kqz0jDRjTM8IjE2JwLjUCFj8eH0IeQ9LgbxiT341Vu8rxncHS3GktF50HMXw02sxoVckZg2IxZQ+0SwI8jiWAnlMVmENvswswlf7ipFf2SQ6juKxIMgbWAp0QQqqGrFqdyE+3V2InLIG0XFUy0+vxcS0SMzsH4vpfWN46St1GUuBOq3FasPne4vwv50FyMitBL+CpCXIpMflQ7pjwcgEpEYHio5DMsNSoPNWWN2E97acwPKMPFQ1crFYDkYmheG6UYmYkR4Do55bndG5sRTonDbnlOOdzSewLruEl4/KVITFiHnD4nHtyAR0Dw0QHYckjKVA7WpsbcOqXYV4Z0suDpfw6iGl0GqACb2icMfEZIxMChcdhySIpUBnqWmyYumPx/DfLbmK2FqCOjYiKQy/nZyCi1IjRUchCWEpEACgtsmK/2w6hmWbclHXwjJQkyEJIVgyORWTe0eJjkISwFJQudpmK5ZtOo43Nx1HbTPLQM36dQvCkkmpuLhfjOgoJBBLQaXqW9qw7Kfj+M+Px7ntBJ0lLToQ903rxXJQKZaCyrS02bDsp1y8sTGHl5WSW6OSw/CX3/RFelyw6CjkQywFFVmfXYInvjyA3IpG0VFIJrQa4Mqh8XhgRhoiA/1ExyEfYCmoQG55A/765QF8d7BUdBSSKYufHndN7ImbL0riuFGFYykoWGNrG/713VG8uel4l2YTE/1SfJg/Hr6kD2b2jxUdhbyEpaBQX+wtwtNfZ6O4pll0FFKg0T3D8ezl/ZEYbhYdhTyMpaAweRWNeGhlJrbkVIiOQgrnb9DhwYvTsGhskugo5EEsBQX5YNsJPPVVNhpabaKjkIoM7xGKv105EEkRPGpQApaCApTUNuOhjzOx4XCZ6CikUiaDFr+fnoabxyZBq9WIjkMXgKUgc5/uLsSjn+/nDWgkCUMSQvH3KwegZ5RFdBTqIpaCTFU2tOJPq/ZhddZJ0VGIzuKn1+KBGWm45aJk0VGoC1gKMrQ+uwR/+GQfyupbREch6tD0vtH4x1UDEeRvEB2FOoGlICN2uwP/+OYQXtuYwxGYJAsJYQF4dcEQ9OvGrTLkgqUgE1UNrbh7+W78eKRcdBSiTvHTa/HIb/piwahE0VHoPLAUZCCzoBp3vb8LBVVNoqMQddmcQXF45vL+CDDqRUchN1gKEvdRRj4e+SyL21SQIqREWfDqgiHoFR0oOgp1gKUgUS1tNjz62X4sz8gXHYXIo/wNOjx/9UBc0o/7J0mRVnQA0R577DFoNJqzfvTu3VtoptLaZsx7fQsLgRSpyWrDXe/vwusbckRHoXbw5B6A9PR0rFu3zvVrvV7c/5acsnrc+NZ2rh+QojkcwLNrDuJYeQOeuqwfDDrVf38qGSwFOEsgJkb86MHdeVW46e0MTkQj1VixIx8FVY14/fqhCDLxfgYpYD0DOHLkCOLi4pCcnIwFCxYgLy/P5xnWZ5fg2qXbWAikOptzKnD1G1tQUstt3qVA9QvNq1evRn19PdLS0lBcXIzHH38chYWFyMrKQmCgb66Q+CgjH39ctQ82u6r/KkjluoX44+1Fw5HKK5OEUn0p/FJ1dTUSExPx/PPP4+abb/b66724/gj++e1hr78OkRwE+xuwbOFwDEkMFR1FtXj66BdCQkLQq1cvHD161KuvY7c78KdV+1gIRGeoabLihre2Y+eJKtFRVIul8Av19fXIyclBbKz3rqG22x144OO9eH+b79cuiKSuvqUNN7y5DTtyK0VHUSXVl8L999+PjRs3Ijc3F5s3b8Zll10GnU6H+fPne+01H161D5/sKvTa8xPJXUOrDTe+tR0ZLAafU30pFBQUYP78+UhLS8O8efMQHh6OrVu3IjIy0iuv9+dV+/ARb0ojOqeGVhsWvrUd24+zGHyJC80+9Njn+/H25lzRMYhkJcCow7JFwzEyKVx0FFVQ/ZGCrzz51QEWAlEXNLbasGhZBrYdqxAdRRVYCj7w3OqD+M+Px0XHIJKtxlYbFr2dgT351aKjKB5LwcteWHcYr23kxl9EF6qx1Yab387AiYoG0VEUjaXgRR9sO4EX1h0RHYNIMSoaWrFwWQYqG1pFR1EsloKXfHewFH/5bL/oGESKc7y8Abe8k4Fmq010FEViKXjBvoIaLPlgF/cyIvKSXXnVuPvD3bDz35jHsRQ8rLC6CTe9k4HGVn4XQ+RN3xwowaOf82jc01gKHtTQ0oZb3slAWV2L6ChEqvDu1hN4nRdyeBRLwUPsdgfu/WgPsovrREchUpXn1hzE6qxi0TEUg6XgIc+tOYhvD5SIjkGkOg4H8MD/MnGsrF50FEVgKXjA6qxivPHDMdExiFSrvqUNd763C01cy7tgLIULlFfRiIc+zhQdg0j1DpXU4Y+r9omOIXsshQvQ2mbH4g92oba5TXQUIgKwanch3tt6QnQMWWMpXICnv87GvsIa0TGI6Ax//eIA9nKPpC5jKXTRmqyT3PWUSIJabc4j+OpGboXRFSyFLsivbMSDH+8VHYOIOlBQ1YR7l+8RHUOWWAqd1NpmxxKuIxBJ3obDZTya7wKWQif9be1B7C3gOgKRHDy3+iC32u4klkIn7DxRhbc2cVgOkVw0WW24/397uXFeJ7AUzlNLmw0PfpwJfm0RyUtGbhWWbeY3c+eLpXCeXlp/FDm8jZ5Ilv6+9hC3wThPLIXzcKCoBm9wJ0Yi2Wq22nH//zJ5Guk8sBTOoc1mxwMfZ6KNX0xEsrYrrwpLf+QeZefCUjiHpT8ew/6iWtExiMgDnv/2MHJKeRrJHZaCGzll9Xhh3RHRMYjIQ1ra7Hj8C05rc4el4MYfV+5DS5tddAwi8qAfjpRz9okbLIUOfL2vGNuOV4qOQURe8NRXB9DKb/jaxVJoR2ubHc+uPig6BhF5SW5FI29E7QBLoR3vbMlFXmWj6BhE5EX/+v4oyuqaRceQHJbCL1Q1tOLl77i4TKR09S1teG7NIdExJIel8AsvrD+C2ibugEqkBp/sKsAeDuQ5C0vhDDll9Xifo/yIVMPhAB7/nJeonomlcIZnvs7mnctEKrM7vxrf7D8pOoZksBRO2ZJTgXXZpaJjEJEAL67nOuJpLIVTXlh3WHQEIhJkf1Et1mXzhjaApQAA2JFbyRvViFTuRW5pA4ClAAB45Xtui02kdvsKa/DdQZ5C1osOINqBohp8f0g+XwhtdeWo3vA2mo7thKOtBfqQWITPvBd+sakAgBPP/abdPxcycRGCR17R4fPW7foSNdtWwtZQBWNUEsKm3g6/uDTX45Xrl6Ihaz00BhNCJtwIS/ok12MNBzehIWs9oq581EOfJZEYL60/gsm9o0THEEr1pSCnowRbcz1OvvcgTAkDEHXVY9AGBKOtqghak8X1Md0Xv3vWn2k6tgMVq19CQNrYDp+3IfsHVH73H4RPXwxjXBrqdnyG0hWPIO7WN6Azh6Dx6DY0ZG9E1Lwn0FZVhIrVL8I/aQh0AcGwtzSg+of/IvqaJ732eRP5yp78amw8VIoJaeotBlWfPjpWVo/VWcWiY5y32q0fQx8UgYhZ98IvLg2GkBj4Jw2BITTW9TE6S+hZPxqPboMpsT8MITEdP2/GpwgcOAOWAdNgjEhA2IzF0Bj8UL/vWwCAtSIfpvj+8ItNhbnvBGiMAWircS7KVX2/DIGDZ0IfpN5/RKQsar8SSdWl8NrGHMjptoSmo9tgjElF2afPIP/lBShadjfq9qzp8ONtDVVoysmAZcD0Dj/GYbOi9eRRmBIHuX5Po9HC1GMQWgqdmwIaI5PQevIobM31aDl51HnaKjQOzQX70VqSg8Chsz32ORKJtiuvGptzykXHEEa1p48Kq5vw6e5C0TE6xVp9EtbdXyNo+FxEj56HluIjqFr/b2h0Blj6T/nVx9dnrYfW6I+AXmM6fE5bYy3gsENnDjnr93UBIbBWFAAA/JOHwpw+ESffuQ8avRERs+6D1uCHyrWvInzWfajb/TXqdn0JnX8QwmYsgTEy0aOfN5GvvbP5BMb0jBAdQwjVlsKyn47DapPRYQIAOBzwi0lB6IQbAQDG6J6wlp9A3Z6v2y+FzHUw950Ijd54wS8dMm4BQsYtcP26etMHMPUYBI1Wh5otHyHuplfQdHQ7Kr56HrELX7zg1yMSaV12CYprmhAb7C86is+p8vRRS5sNH+8sEB2j03SWUBgiEs76PUN4PGy1Zb/62Ob8LLRVFsAysONTRwCgCwgCNFrYGqrP+n1bYzV05tB2/4y1Ih8NB75HyEXXoTlvH0zd+0EXEIyA3hehtSQH9hZuO07yZrM78MG2PNExhFBlKazedxLVjVbRMTrNr1tfWCvPLjNrZWG7i7z1md/CGJMCY1Sy2+fU6AwwxqSg+cRe1+85HHY05+6FX7fev/p4h8OBirWvIHTyLdAa/QGHHQ77qV1lT//s4EQrkr/l2/Nhtanva1mVpfDhdnl+BxA0fA5aig6hZssKWKuK0HBgA+r3roFlyKyzPs7e0ojGQ5s6XGAuWf5H1O784oznnYu6vWtRv289rOX5qFz7KhzWZlj6T/3Vn63fuxY6/yAEpIwEAPh164PmE5loKTyI2ozPYAhPOOsSWSK5KqtvwZos9W2Up7o1hZzSetluaeEX2wuRl/0J1RvfQfVPH0IfHI3QybeedSMZ4LzvAA7A3HdCu89jrToJv6Za16/NfcbD1liD6k3vnbp5LRlR8/76q9NHtoYq1GxZgZjr/v5zprg0BI24DKUfPw5tQDAiZt3nwc+YSKz/bsnF7IFxomP4lMbhcMhstfXCPPHlAbzJ2axEdJ7W3HsRescEiY7hM6o6fdTSZsPKXfJbYCYicd7doq7BW6oqhTVZJ1ElwwVmIhLn092FaLbaRMfwGVWtKch1gZmIxAgJ0OOuiSkwGXSio/iMakqhoKoRW4/Jc4GZiHzHbNTjzkk9MXdQHLqF+EOj0YiO5FOqKQU1XlpGZwv2NyAlyoLQAANCA4wICTAiJMCA0AADzH56NLbaUNfchrpmq+vnmiYrcisakVvewPndCmbSa3Hr+GRcMbQ7EsMCVFcEZ1JNKaxmKaiKv0GHft2CMKB7CAZ2D8aA7iHoEWHu8vO1ttmRU1aP/UU12JNXjd351cgurpXVhop0NqNei4VjEjFvWAKSI83QqrgIzqSKS1JLapsx6pn1UP5nqm4xQSZc3C8Gl/SLwbAeYdBpvfuPvKyuGauzTuKrzGJk5FayIGRAqwWuH9UD146IR2pUILRe/hqRI1WUwn+35OKRz/aLjkFeYDbqMLN/LK4c2h0jk8OF5SitPVUQ+4qxXaY3RyrZNcPjcf2oRPSODfL6Nwtyp4pSmL90K7bkVIiOQR4UGeiHOyf0xDUj4hFglNZZ0OziWrz83RGszjrJo1OB5g6Ow8IxSegXFwS9TlVX318QxZdCZUMrhj+1DjYe2ytChMWI2yf0xPWjEiV/meCRkjq88n0Ovsgs4tefj1zSLwY3j0vCwPgQGDxVBNYm4Mg3QNZKwGEDrn7PM88rUYovheUZefjDJ/tEx6ALFGY24rbxybhxdA/4G6VdBr+UW96Al747gpW75DXUSS4mpUXitvE9MTQxBEa9h7422lqAo+uA/SuBQ2uA1nrn7+sMwEO5gFG5mz4qvhQWvrUdGw7/et4AycfcQd3w1znpCPI3iI5yQX44XIaHV+5DYXWT6CiyNyo5DHdNTMGIpDDPHTHarMCxDc4iOPgV0FzT/sdduwLoNcMzrylBii6FZqsNAx77Bq0q3BNdCcLMRjx1WT9c0i9WdBSPqW9pwzNfZ+OD7Xlcb+ikIfEhWDw5BaN7hntuHcluA3J/dJ4ayv4caKo6958ZdSdw8bOeeX0JktYKnYftyK1iIcjU9L7RePry/oiw+ImO4lEWPz2euqw/ZvaPxUOfZKKgikcN7vSNDcTdU1IxLiUSFpOH3q4cdiBvi7MIDnwGNHTyTELO957JIVGKLoUtx3jFkdz46bV4cm4/XDUsXnQUrxqbEoE1947HPct3Y312qeg4kpISacbdU1IxMS0KgSa95+4uzt/uPDW0/1Ogrrjrz1N2EKgtAoKUOWdB2aXAy1BlJcikx9Ibhgm938CXLH56LL1+GJ5dcxD//uGY6DhCxYf6456pvTClTxRC/A2eK4KiPUDWJ8D+VUBNvmeeE3CuPQy61nPPJyGKLYWGljZkFlSLjkHnKSbIhLdvGq6qYSYAoNVq8MeZfdAj3Iy/fJalqktXY4NMuHtKCqanxyDMbPRcEZRkAVmrnEcFlV4qW5aC/OzIreQGZjKRGmXBOzeNQFyIv+gowlw7MgHhFiPu/nA3WtqUuw4WYTFiyeRUzOwXg8hAP88VQdkhZwlkrQTKD3vmOd05tsH7ryGIYkuB6wnyMCQhBMsWjUCwzC839YQZ6TF488bhuOntDEVdIBHsr8fiSSmYPSAOMcEmzxVB5fGfi6AkyzPPeb7qS4CS/UB0um9f1weUWwpcT5C81CgLC+EXxqVG4LkrB+C+j/aIjnJBzEY97pyYjDmDuqF7qAdnEtTk/3xqqGi3Z56zq3I3sRTkoq7ZiqyiWtExyI3YYBPeuYmF0J7LBndDUXUT/r72kOgoneKaSTCkOxLDPTiToK7YecXQ/pVAQQYkc4OH6FLyEkWWwq4TVapasJObAKMOby0cruo1hHNZPCkFRdVNeH+btEfIGvVaLBydiHnDPTyToKHMeQ9B1krnPQUOCZ5OK94jOoFXKLIUMgs7uD2dhNNogOfnDUKfWHVdZdQVf53TDydrmyV3H4NzJkEi5o9IQC9PziRoqgKyv3AWQe4PzruNpaz8MNDaABi7PrxJihRZClmFPHUkVYsnpeDifjGiY8iCTqvBP68ehIv/+QOKappFx8E1w+Jx/WgPzyRornHuM7R/pfOKHpvVM8/rC3YbcHIfkDBKdBKPUmQp7C/ikYIU9YkNxD1TUkXHkJUgkwHPXjEAN7y1XcjrzxkUh0Vje6BfXLDnZhK01jt3Ht2/0rkTaVuLZ55XhKLdLAWpq2po5X4yEqTTavDcFQM8t8e9iozvFYn5I+Lx4XYP3pHrhtdnEhxZ6/y1EihwXUFxpXDwZJ3oCNSOW8YlYUD3ENExZOtPs/rixyPlXvuGxyszCWytziOBrE/OnkmgJAq8AkmBpcD1BKlJijDjvmm9RMeQNYufHs9dMQDXvbnNY1dkCp1JoBTlR5xlp6ChO4orhUM8UpCcZy/vL/nRmXIwNiUCcwZ2w6d7uj7BzXszCTY5jwjOdyaBUjjsQMkBIH6E6CQeo7hSOFzCUpCSiWmRqtn11Bd+OzkFn+8tRGduw5HkTAIlqTzGUpCywyUKPG8pY0smpYiOoCg9oyz4zYA4fL63yO3HSX4mgZJU5YpO4FGKKoXKhlbUt7SJjkGnjEwKw7AeYaJjKM5vJ6fgy8yiXx0teHUmwf6VzpkE1dK+w1oIloJ0FXEguqQs5lGCV6RGB2Jm/1h8mVks75kESlF1XHQCj2IpkFf07xaM8b0iRcdQrH9dOwSPzG5GpMWDMwnKDzvXCPavdM4noPPDIwXpKmQpSMZt45NFR1C8qEDThT+JyJkESlF30nkznkEZGzwqqhSKqsXvD0OAyaDFlD5RomNQR2rynQvFWZ8o8uYrIapygag+olN4hMJKgUcKUjChV5TnroEnz5DqTAKlYClIE0tBGi7hLqjSIIeZBEpRfUJ0Ao9RVClwTUE8o46njoSS20wCpWgoF53AYxRTClabHeX1Mt6CVyHGpUYg0MQRmz7VWg8c+FyeMwmUQkFbeyimFCrqWzt16z95x1QeJfjesplA8V7RKdStuVp0Ao9RzOb2DbyTWRIGJ4SKjqA+ClnglDUFHSkophS4vYV4JoMWqVHK2UJYNmIHiU5ALAXpaWhlKYjWNzbIcyMb6fzFDRKdgJqqRSfwGMX8C+bpI/FSowNFR1CnmAGARjH/lOWJRwrSU9/CS+9E46kjQYxmIIKT7YRS0IQ5xZQCjxTE6xnJUhAmuJvoBOrmsCvmCiTFlAIXmsULNRtFR1AvU4joBNSmjPukFFMKPFIQz+KnmNte5MeflwILp5D9pBRTCo2tXFMQzeynEx1BvVgKEsBSIDqLmUcK4viHiE5APFKQFp3WQ9OnqMvM3C5bHH/OwhaPpSApepaCUCaDlsVM6qaQrckVUwp8QxKrzaaM75JkS0HXycsWTx9JC48UxGqzO1DTxC2bhWmpFZ2AePpIWrQsBeEqOM9CnGaWgnDK6ATllAKPFMSrauSRgjA8fSSeVhlvp8r4LADoFPIXImeVDTxSEIanj8TzCxKdwCMU807KIwXxKhpaRUdQr7pi0QnUTaMFTMGiU3iEYkrB38i7aUXLr2wSHUG9yg6JTqBufsrZNl4xpRDGzdiE25tfLTqCOtUUcE1BNIUcJQAsBfKgzIJq0RHUqWS/6ASkkPUEgKVAHlTb3IajpfWiY6hP4Q7RCYhHCtITFsBSkII9+coZSygbBSwF4Uw8UpCcULORW11IwJ68atER1MXWylKQAh4pSFNogEF0BNXberxSdAR1yfme9yhIgYIm3ymsFHgKSbSjpfU4UlInOoZ6HPhMdAICgODuohN4jKJKIdzCUpCCr/fxRiqfsFmBQ1+LTkEAEJIoOoHHKKoUIix+oiMQgM/3shR84tgGoIkL+5IQkiA6gccoqhQSwgJERyAAOWX12HWCb1Zed+BT0QnoNJaCNCVFmEVHoFNW7MgXHUHZmmuA7C9EpyDAucVFgHLGobIUyCu+2FuE6kZukOc125dyawupCI4XncCjWArkFQ2tNryx8ZjoGMrU2gBsfVV0CjotVDmLzIDCSiHc4ocgf73oGHTK25tzUVbHGQset3MZ0FghOgWdpqD1BEBhpQAASeE8WpCKJqsNr204KjqGsrS1AJtfFp2CzsRSkLakCIvoCHSG97flobiGcxY8Zve7QN1J0SnoTBFpohN4lPJKIZJHClLS0mbHv77j0YJH1JcA3z0pOgX9UnS66AQepbhSSOZis+R8uD0PO3K5J9IF++r3vFlNagLCgKA40Sk8SnGl0CdWOVvYKoXdAfxuxV40tLSJjiJf+z/lfQlSFN1PdAKPU1wppERZEGTiFUhSk1fZiL9+eUB0DHlqrAS+vl90CmoPS0EeBsaHiI5A7fgoIx/fHigRHUN+1vwBaCgTnYLaEzdYdAKPU2QpDGIpSNbDKzNRXs97F87bzneAzI9Ep6COsBTkgaUgXeX1rbjzvZ1ottpER5G+E5uBr38vOgV1xC8IiEgVncLjWArkcxm5VVjywS7Y7A7RUaSrKhdYcYNzZgJJU+xA0Qm8QpGlEG7xQ3yYv+gY5Ma67FI8vHKf6BjS1FAOvHsZ1xGkLmGk6AReochSAIDB8aGiI9A5rNiRj7+tOSg6hrS01AIfXAVUcjNByUuaIDqBVyi2FHgKSR5e3ZCDpT/yDRCAc/uKZTOBwl2ik9C56E1A/AjRKbxCsaUwvIdyhl4o3VNfZePZ1dmiY4hVfgR4cxpwkqfUZCFhlLMYFEixpdC/ezAiLEbRMeg8vb7xGO5ZvhstbSq8KqlgB/DWDKA6T3QSOl8KPXUEKLgUAGB8r0jREagTPttThGve2IqS2mbRUXzn8BrgndmcjyA3ySwFWZrIUpCd3fnVmP3yJmQofQM9axPw9QPAh9cA1kbRaagzTMFA7CDRKbxG0aVwUWoktBrRKaizSutacPUbW/DY5/uVuYle4U7gjYuA7f8GHLxXQ3YSxwJanegUXqPoUgg1G3kVkkzZHc5xntP/+QO+P1gqOo5n2KzA9085F5TLj4hOQ12l4FNHgMJLAQAmpEWJjkAXoLC6CYvezsDdH+5GhZz3TDq6Hlg6Gdj4N8CuwsV0JUmZJjqBV2kcDmUfv+7Nr8acV34SHYM8INjfgBvHJGLhmCSEmWVyZVnuj8B3TwF5W0QnIU+I6Q/csUl0Cq9SfCkAwNAnvkVFQ6voGOQh/gYdrh4ej1vHJ6NbiES3M8nf5iyD4xtFJyFPmvxnYPwDolN4lSpK4f7/7cXHOwtExyAP02s1uHRQHG4el4T0uGDRcYDWBmD/KmD3ezwyUKolOxS5M+qZVFEKGw6VYuGyDNExyIsSwwMwvW8MZqRHY0hCKLS+uuzM1upcLzjwKZD9JdBa75vXJd+LTgfu3Cw6hdepohTabHaMeHo9KnkKSRUiLX6Y2jcKz1w+wPNP3toAFO1y3oVcsMO5ZtBc4/nXIemZ9CdgwoOiU3idKoYZ63VazOwXg/e2cRsBNSirb8GmI+XuP6g0G9D7AUYzYAhw/qzRAvY259bVDWXOu4wbypy/LjsEFO4ASg/w6iG1Sp8rOoFPqKIUAGD2oDiWgopM6RPd8YPFmc6bx35JbwJsLbyhjH4tqi8Q0Ut0Cp9Q/H0Kp41MCkf3UIleqUIeN6yHm3kapfvb//22ZhYCtU8lRwmAikoBAC4b3E10BPKRtOjAjh8sOeC7ICR/Gg3Qf57oFD6jqlK4fEh30RHIR2KD3RwVdnSkQNSe5ElAWJLoFD6jqlJIijBjaCLHdCqdVguY/dxsWMYjBeqMYTeJTuBTqlloPu3q4fHYeaJKdAzyoqEJodBoOrhPoakKqCv2bSAvey2jFa/taEVutR0AkB6lwyPjjbgk1QAAuP2LJqw73oaiOgcsRg3GxOvw3FQ/9I7ouDgdDgce3dCCpbusqG52YGy8Dq/NMiE13PlnWtocuOWLZnx20IoYixavzjJhavLPbyd//6kFeTV2vDxT5ut4gbFA2iWiU/iUqo4UAGDOwDj57JtDXeJ2uFKJ8k4ddQ/S4Nmpfth5mxk7bjNjcg8d5ixvwv5S56WzQ+N0WDbHH9mLLVh7XQAcDmD6u42w2TteVP/bT614aVsrXp9lwrZbzDAbNZjxXiOa25x/5t87rdhZZMOWm824bagB137ShNO3PB2vsmPpLiuemqKAcZVDrge06vreWXWl4GfQYf6IBNExyIvcbpeuwFKYnWbAzFQDUsN16BWuw1NTTLAYga0FzlK4bagR4xP16BGixZBYHZ6c7If8Wgdyq9svBYfDgRe2teLP4/0wp7cBA6J1+O9cfxTVOfDpQed8i+xyGy5N0yM9SofFw40oa3SgvNH5fHd+1YTnpvohyE/mw0y0OmDIjaJT+JzqSgEArh+VCD2n7yhWcoSl4wdLlb2eYLM7sDzLigYrMDr+16eHGlodWLbbiqQQDeKD2/83cLzagZP1jrNOBwWbNBjZXYct+c6iGRitw6Y8G5qsDqzNaUOsRYOIAA3ez7TCpNfgsj4G73yCvpQyDQhW38Up6jouOiUm2ISZ/WPx+d4i0VHICyIC3ZweVOCRAgDsK7Fh9JsNaG4DLEZg1dX+6Bv5cym8mtGKB79tRoMVSAvX4tvrzTDq2i+Fk/XOtYlo89mPR5s1ONngfOymwQZkltjQ99V6RARosOIqf1Q1A49saMaGG83483fNWJ5lRc8wLd661B/dgmT4/afKFphPk+HflGcsGttDdATyArNRD6POzZd1abbvwvhQWoQWe+6wYNstZtw5zIgbP23GgbKft+NY0N+A3bebsXFhAHqFazHv45/XB7rCoNPglVn+OH5PIDJutWBcgh6//6YZd48wYvdJGz492Ia9d1gwqpsOd69p9sSn6FshCUCqsofpdES1pTA4IRSDOapTcSakRXR85VHVCcXuYmrUaZASpsXQOB2emWrCwGgtXtz68waQwSYNUsN1GJ+ox8fz/HGw3I5V2e3Pv46xON8WShrOLo2SBgdizO2/ZXx/vA37S21YMsKIDbk2zEzVw2zUYF66ARtyZbhX1JjfOvfCUiF1ftan8GhBecb2jOj4QRXdtGZ3AC0dvBc7HM4fLbb2jxSSQjSIsWiw/tjPpVHb4sC2Alu76xTNbQ4s/roZb/zGHzqtBjY7YD312lY73F7lJEmWaGDIDaJTCKPqUrikfyyig/xExyAPSu8W1PGDCr1p7eF1zfjhRBtyq+3YV2LDw+uasSHXhgX9DThWZcczP7ZgZ5ENeTV2bM5vw1X/a4K/QYOZqT8vKfb+Vz1WZVsBABqNBveONOLJH1vw+SEr9pXYcMOqJsQFajC396+XIZ/Y2IKZqXoMjnUWxtgEHVYetCKzxIZ/bW/F2ASZLV2OXuLcHFGlZPa35VkGnRa3jU/GE18q8zyzGsWHBnT8oEIXmUsbHLhhVROK6x0I9tNgQLQWa68LwLSeehTV2fFjng0vbGtFVZMD0RYNxifqsPmmAESdcSroUIUdNS0/f0f/4FgjGqwO3PZFM6qbHRiXoMOa6wJg0p99ai6r1IYVB9qw53az6/eu7KvHhlw9LlrWgLRwLT64ws3fidT4hwLD1bnAfJoqhuy402K1Yfzfv0dJbYvoKOQBOU/PhK6jy41fGeGci0DUkUl/BCY8JDqFUKo+fQQ4b2ZbMknZM1fVoluoqeNCaGsBKnJ8G4jkxS8IGHm76BTCqb4UAOd+SJy1IH9T3Q3WKT/knKpG1JHhtwCmENEphGMpADDqtbh7Co8W5G5YYljHDyp0kZk8xBAAjF4sOoUksBROuWJIdyRFmM/9gSRZvWPcDNZR+PYWdIFG3gGY3VzOrCIshVN0Wg3uncqjBTlzO1hHoVcekQeYI4GLfic6hWSwFM4we0Cc+zGOJGnuB+uwFKgDk/8M+PHf/WkshTNotRrcP6OX6BjUBcMS1TVYhzwkOh0YfL3oFJLCUviFaX1jMMHdkBaSpPG93JwP5lECdWTG0865CeTCUmjHY5emu99pkyRnULyb2dtcZKb29JoBJE8UnUJy+M7XjqQIM24dnyw6BnVCcqSbK8d4OSr9klYPTH9SdApJYil0YMmkFN7QJiORgW42NlTR7qh0nobdBERw/bA9LIUO+Bt1+Mtv+oqOQedBrYN1qIvMkc49jqhdLAU3ZqTHYCIXnSXvnIN1Wup8G4ikbeY/nLuhUrtYCufw2KXp8NPzf5OUjU7mYB06T31mA+lzRaeQNL7bnUOPCDNun8BFZynrp8LBOtQF/qHArP8TnULyWArn4beTU5Ee5+aNh4RKCHMzxIWXo9JpM55yjtokt1gK58Gg0+KfVw/iaSSJCgkwdPwgb1wjAEiZAgxaIDqFLPBd7jz1ig7EgxeniY5Bv+AcrNPBl7GtFag46ttAJD1+gcDsF0WnkA2WQifcPC4ZY3qGi45BZ3A7WKeMg3UIwNTHgOB40Slkg6XQSf+4aiCCTHrRMegU94N1eOpI9VKnOSeq0XljKXRSXIg/Hp/TT3QMOoWDdahDQd2Ay94QnUJ2WApdcNngbvjNgFjRMQhAbLCp4wd5pKBeWj1w5VtAAE/3dhZLoYuenNuPeyNJgNnPzak8Himo1+Q/AwmjRKeQJZZCF4UEGPH6dUN5mapAQxLcDdapBmqLfJqHJCJ1GjDuPtEpZIvvaBegX7dgPHN5f9ExVGtiGre3oF/gOsIFYylcoMuHdMfCMT1Ex1Alt4N1uL2F+nAdwSNYCh7w51l9MDLJzaWR5BXuB+vwSEF1pjzKdQQPYCl4gF6nxSsLhri/EoY8LtLCwTp0ysD5wNi7RadQBJaCh0RY/PAaF559JsCohdHd/2sO1lGPhFHApS+JTqEYfAfzoEHxIXhiLm9s84UJvaI6vvKomoN1VCMkEbj6fUBnFJ1EMVgKHjZvWDx+OzlFdAzFG9PTzZVHXGRWB1MIcO1HgNnN1wJ1GkvBC34/PQ3XjkgQHUPR3A7W4U1ryqczAle/C0T1EZ1EcVgKXvLE3H6YkR4jOoZiuR2swyuPlE2jAea8AiSNF51EkVgKXqLTavDS/EEYlcxLVb2Bg3VUbMqjwIB5olMoFkvBi/z0Ovz7hmHoG8tRnp7EwToqNv4BbmHhZSwFLwsyGfDOTcPdn+6gTpmcFtXxgxyso1xj73VudEdexVLwgchAE969eYT7m63ovA1PcrONAReZlWnUXcC0x0WnUAWWgo8khpux/LZRiA5iMVwot4N1eDmq8gy/Bbj4Ga+/zLPPPguNRoN7773X668lZSwFH+oZZcGK20ejWwjnMFyIOHfbiXB7C2UZuhCY9X9ef5mMjAy88cYbGDBggNdfS+pYCj6WGG7GijtGIzGcawxd5XawDo8UlGPQAmD2i15/mfr6eixYsABLly5FaKibnXdVgqUgQLcQf6y4fTRSoiyio8jOuQfrFPo0D3nJoAXAnH/55KUWL16MWbNmYerUqT55PaljKQgSHWTC8ttGoU+sm/Pj9CsTenGwjuJd9Htg7quAxvtvT8uXL8euXbvwzDPeX7OQC5aCQBEWP3x46ygM6B4sOopsDEoI6fhBnjqSN40WmPl3YMojPnm5/Px83HPPPXj//fdhMnHb+9NYCoKFBBjx3i0jeefzeeoZ6eaUGy9HlS+9H3DlMmDEbT57yZ07d6K0tBRDhgyBXq+HXq/Hxo0b8dJLL0Gv18Nms/ksi5S4WbEjXwkyGfDfm0bioU8ysWo3z4m74/ZeD25vIU+mYOCa94EeF/n0ZadMmYJ9+/ad9XuLFi1C79698dBDD0Gn0/k0j1SwFCTCqNfin1cPQmJ4AF5Yd0R0HEniYB0FCowBrvsEiPb9HJLAwED063f265rNZoSHh//q99WEp48k5t6pvfD8vIGc4NYO94N18oCWWt8GogsTmQbc/K2QQqCO8UhBgi4f0h09ws24/d2dKKtvER1HMkb3dLO9BU8dyUvfOc4rjIzSuix7w4YNoiMIx29HJWpIYig+WzIW6XHcYfW0ft3cXKXFRWZ50OqAaX8F5v1XcoVATiwFCYsL8cfHd4zBpQPjREeRBA7WkbmAcOC6VcDYe0QnITdYChLnb9ThpfmD8fRl/WEyqPuvy+1gHR4pSFvcYOD2jUDyBNFJ6BzU/S4jI9eOTMBni8chVaVbY3QLMUHvbrBOOa/YkqzB1wE3rQGC40UnofPAUpCRtJhAfL5kHK4Zrr5/XJN7uxmsU36Yg3WkyGgGZr/knKes5x3DcsFSkBl/ow7PXjEAL88fjEB3u4UqjNvBOtzeQnriRwJ3/AQMvVF0EuokloJMzR4Yhy/vHqeafZPcD9bhIrNk6IzAlEeBRauBsCTRaagLWAoylhhuxid3jsHdU1Jg0HVwU5dCxHKwjvRFpwO3fgdc9DvnpackSywFmTPotPjdtDR8+duLMMTdDqIyZ+FgHenSaIGx9wK3bQBi+otOQxeIpaAQaTGB+PiOMXjs0nSYjcr6Lm1wfHDH21s0V3OwjkhhycCir4FpjztPHZHssRQURKvVYOGYHvj2dxPcX60jMxPS3HwuPEoQwxAATP4LcNdWIGG06DTkQSwFBYoL8cdbC4fj5fmDEWGR/3dvg92dFuNNa77X51JgyXZg/P3OOQikKOq5plGFZg+Mw0WpEfi/bw7jw+15aLM7REfqEreDdXik4DvhKc7JaD0ni05CXsQjBYULCTDiibn9sPa+8ZiRHi06TpdEuB2sk+W7IGplNANTHwPu2sJCUAEeKahEz0gL3rh+GDJyK/H0V9nYnV8tOtJ5CTBq3c+W4GAd79Fogf5XOu87CO4uOg35CEtBZYb3CMOqxWPxVWYx/rb2IE5UNIqO5NZFKZEcrONrGg3Qdy4w8Q9AZG/RacjHWAoqNWtALKb1jcb7207gpfVHUNVoFR2pXWNSIjp+kIvMnpc2E5j0R95voGIsBRUz6rVYNDYJVw+Px4fb8/CfH4+juKZZdKyz9Hc3WIeLzJ6TMhWY9Ceg2xDRSUgwlgIhwKjHzeOSccPoHvh0dyFe33gMOWX1omMBABLC3QzW4fYWFy55EjDpYecGdkRgKdAZDDotrhoWj6uGxeOb/Sfx2oYc4QvSbgfr8Eiha/QmYMA8YOQdzv2KiM7AUqB2TU+PwfT0GGw9VoHXN+Rgw+Eyn2c452CdCg7W6ZSgOGD4LcDQhc7RmETtYCmQW6OSwzEqORzHyxuwIiMfH+8qQFldi09ee5K77S3KDwM2aS6OS078CGDknUDfSwEt/8mTe/wKofOSFGHGQ5f0xu+n98J3B0uxPCMfGw+XwebFu6RHJIV1/CBPHblntADpc4FhN3PxmDqFpUCdotdpXaeWTtY0438787FiRz7yK5s8/lppMUEdP8jLUX9NowWSJgCD5gN9Zjs3rSPqJI3D4ZDnhjgkKZtzyvFVZjG+OVDisdNL+x6bjkBTBwvN718FHPnGI68je3FDgH6XO38EdROdhmSOpUAeZbc7sCuvCmv3l2Dt/pPIq+z6HdPHn5nZ8d3M/0wHagq6/NyyptEAMQOB3rOAflcA4T1FJyIFYSmQV2UX1+Kb/Sexdn8JDhSf/5YUg+ODsWrxuPYfbK4Gnk30TEC58A91bkaXMtX5w6KceRkkLVxTIK/qExuEPrFBuGdqL+RXNmLT0XJsO1aJbccr3N49Pb6XygfrnD4aSJ0KpEwDug/n3GPyCZYC+Ux8WADmj0jA/BEJAID8ykZsO16BbccqsfV4xVmL1aobrKP3A2IHAt2GOQugx1jAIs+tzkneWAokTHxYAOLDAnDl0HgAQFF1E7Yfr8SuvCqM6KHwy1FDk4Duw079GO7cgI4zjkkCuKZA8vPObOD4D6JTnJtG65xDEJ7qXAyOSHVOL4sZAJjd7P5KJBBLgeSp4ihQUwjUFgK1Rad+FJz6uRBorPR+BkMAYI50vsGbI50/wpKdb/zhPZ0/9Cbv5yDyIJYCKVNbM1BbDDTXANYGoLURaG049d+nf10PWBsBe5vz1I3WAOj0p342OLeE0Bmcj+n9gICIUwVwqgR4cxgpEEuBiIhc3Ay/JSIitWEpEBGRC0uBiIhcWApEROTCUiAiIheWAhERubAUiIjIhaVAREQuLAUiInJhKRARkQtLgYiIXFgKRETkwlIgIiIXlgIREbmwFIiIyIWlQERELiwFIiJyYSkQEZELS4GIiFxYCkRE5MJSICIiF5YCERG5sBSIiMiFpUBERC4sBSIicmEpEBGRC0uBiIhcWApEROTCUiAiIheWAhERubAUiIjIhaVAREQuLAUiInJhKRARkQtLgYiIXFgKRETkwlIgIiIXlgIREbmwFIiIyIWlQERELiwFIiJyYSkQEZELS4GIiFxYCkRE5MJSICIiF5YCERG5sBSIiMiFpUBERC4sBSIicvl/yVJw8B/B29YAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "번호를 입력하세요.\n",
      "\n",
      "1. WAN282X1GB Manual Keyword Frequency\n",
      "2. WAN282X1GB Manual Contents Keyword Set Review or Score\n",
      "3. WAN282X1GB Amazon Review Keyword Frequency\n",
      "4. WAN282X1GB Amazon Review or Score\n",
      "5. WAN282X1GB Manual Image Extraction\n",
      "6. Exit\n",
      "\n",
      "2\n",
      "\n",
      "        1. Manual Contents Search(목차 리스트만 출력)\n",
      "        2. Manual Contents Review search(목차와 매칭되는 리뷰 검색)\n",
      "        2\n",
      "\n",
      "추출된 목차 키워드 중 검색 가능한 키워드 목록\n",
      "--------------------------------------------------------------------------------\n",
      "['appliance', 'care', 'cleaning', 'connection', 'consumption', 'customer', 'damage', 'display', 'energy', 'installation', 'laundry', 'lock', 'material', 'operation', 'protection', 'time']\n",
      "조회할 키워드를 입력하세요. : time\n",
      "\n",
      "        \n",
      "        1. 리뷰 검색\n",
      "        2. 평점 검색\n",
      "        \n",
      "        1\n",
      "조회할 데이터 개수를 입력하세요.(최대 조회 가능 건수(37건)) : 10\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "\n",
      "조회한 10건의 조회 결과입니다.\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2023-04-30\n",
      "\n",
      "제목 :  Stunning!!!\n",
      "\n",
      "리뷰 내용 :  Video Player is loading.Play VideoPlayMuteCurrent Time 0:00/Duration 0:27Loaded: 44.34%0:00Stream Type LIVESeek to live, currently behind liveLIVERemaining Time -0:27 1xPlayback RateChaptersChaptersDescriptionsdescriptions off, selectedCaptionsCaptions off, selectedAudio TrackFullscreenThis is a modal window.\n",
      "\n",
      "\n",
      " I purchased this 8kg silver inox washing machine to match my Haier silver inox fridge freezer. It's nice and quiet and the Speed Perfect setting halves the time of the setting you choose. Make sure you remove and keep the four bolts from washer to ensure a smooth wash. The spin is a pleasure to the ears as my other machine was rocking and rolling. I've also noticed that the wash results are better and the items even look cleaner. I paid for it to be installed unfortunately there was a leak but I noticed it in time for the guys to come back and rectify error a couple of hours later. It's only been a day but so far so good, I am very pleased! If the performance changes u will update this review.. I have noticed that after a wash cycle there is a puddle of water left in the seal so I'm having to remove it to avoid any future mold.\n",
      "\n",
      "평점 :  4\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2023-01-22\n",
      "\n",
      "제목 :  Would recommend buying this.\n",
      "\n",
      "리뷰 내용 :  This is the most expensive washing machine I’ve owned and can honestly say that it’s the first one that looks like the clothes have came out really clean, even on a short cycle.  My favourite modes are the short ones and I like the fact that you can stop the machine and add any forgotten garments. When you do stop the machine when it’s in action, there is a symbol which tells you if you are able to open the door or not. This saves wasting time wondering if the door will open to add to the wash.\n",
      "\n",
      "평점 :  4\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2023-01-20\n",
      "\n",
      "제목 :  reasonably priced\n",
      "\n",
      "리뷰 내용 :  My old washer I had to retire or should I say it stopped working on Tuesday,  after 13yrs of faithful service I now have an all singing and dancing new Bosch washer arrived today Friday it looks good easy to use though I have only used it a couple of times does as its told and more it even has a night time setting! well worth the money and for a few more pounds they will install and take away your old one and the packaging well impressed with the service from this company thankyou for your speed of delivery and the delivery people were very courteous and considerate x\n",
      "\n",
      "평점 :  5\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2021-05-29\n",
      "\n",
      "제목 :  Not Quite As Good As I Hoped\n",
      "\n",
      "리뷰 내용 :  I love Bosch kitchen products. Our last Washing Machine lasted over 13 years, was used virtually every day and never required an engineer visit or a replacement part.This latest machine is good but it does not excel. It washes well, is incredibly quiet, appears to be well built and still inspires confidence.However:1. The quick wash 15/30 min has a very short max spin speed of 1200 rpm and it's pretty useless.  The washing is not as dry as I would like. Certainly nowhere near as dry as the older Bosch I had. So I either have to spin again at 1400 rpm or select to have the wash only with the 'no drain & spin' option and then when that cycle ends, select the drain and spin option separately at 1400. This increases a 15 minute quick wash time to around 30 mins at least. This is a huge disappointment as the one main benefit of having Bosch over others is their famous 'quick wash' option, which is no longer suitable and certainly a 'downgrade' in performance from previous models. I'm not sure it's the spin speed at fault or rather the length it spins for, which is incredibly short.2. The wash time is ridiculously long. You can shorten most times with 'speed perfect' for smaller loads but for a full load of cotton bedding 3 hours is ludicrous. If like me you prefer to line dry, half the day is gone before you can even put the washing out.3. Bosch has reduced the packaging that the machine is delivered in. A good thing?! well yes and no. I like the fact that it doesn't come in a massive box, it's delivered wrapped in polythene with polystyrene on all 4 corners but there is no protection at all around the door, which protrudes quite a way. So this makes damage to this part especially, highly likely. So even though it's shrouded in polythene, mine arrived with slight damage to the door. I received discount to keep it but even so it's another disappointment because I am forever looking at the very visible front scratches. Personally I would rather have a cardboard box that can be easily recycled than copious amounts of polythene that offer no real protections at all.I expect all the above, spin speed, wash time and packaging are due to the endlessly changing EU regulations on being overly ECO. I just can't see how increasing wash times which in turn increases energy consumption, reducing drying performance which again means extra energy is needed and reduced packaging which will lead to more returns due to damage, increasing C02 pollution in the transport process, are of much benefit to the overall cause.It would be great if the computerised section of these machines could have a firmware update to correct the flaws, which are all down to program software. As it is, this isn’t possible, so I’m left feeling slightly disappointed, which for me is a new experience with regard a Bosch product. I do feel that perhaps I should’ve spent more time researching other brands, as maybe this time I was duped by my brand loyalty.\n",
      "\n",
      "평점 :  3\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2022-04-11\n",
      "\n",
      "제목 :  Quiet, efficient but slower\n",
      "\n",
      "리뷰 내용 :  My 13 year old Bosch washing machine finally died.It had been perfectly reliable up to that point so I stuck with Bosch for its replacement.On arrival it was noticable how much lighter it was compared to the old one.Plumbing it in was simple as it had the same connections.After half a dozen or so loads I can say that it's much quieter than my old machine.The programmes take much longer like for like though.  I presume it's for eco reasons but its the reason I've taken a star off.I often have to shut the door a couple of times and press it in further until it will lock.Clothes have been coming out nicely cleaned but no drier than with my old machine even though the spin speed is now faster.Judging by my smart meter, energy consumption has dropped by quite a bit. Very handy in current times with such high energy bills.It sounds like I'm not too happy with this but its just that my old machine was so good, hence I stuck with Bosch.Hopefully it last as long!I hope you find my review helpful.\n",
      "\n",
      "평점 :  4\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2022-06-23\n",
      "\n",
      "제목 :  A couple of annoying things…\n",
      "\n",
      "리뷰 내용 :  Two issues with this.1. You cannot preset a spin/rinse once the wash is finished. Once it has run the wash cycle you have to manually switch it to the spin/rinse mode and set it off again.2. The beeping. Once it’s finished a cycle it seems to beep on for ages, not two-three times but six-eight. Ok we get it. And no way to modify this other than switching it off.It’s a washing machine and it works and it does what it is supposed to do, but there is a lot of competition. I had a Samsung for 10 years prior and these small things are just annoying enough to make me regret changing brands.\n",
      "\n",
      "평점 :  4\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2021-06-14\n",
      "\n",
      "제목 :  Quiet & effective but some lengthy cycles\n",
      "\n",
      "리뷰 내용 :  This is a very quiet machine in operation.  It has quite a wide range of cycles but it is advisable to study the program parameters if you like to adjust things for yourself, because options are not as wide as you might think from the advertisements.  This model has the higher spin speed of 1400 rpm BUT this is only available in certain programs, as are the temperature variations & the maximum loads.  Yes, this can prevent unintended results but it obviates personal needs & preferences.  Some cycles seem ridiculously long for their purpose:  the standard cottons program taking 3 hours.  The manual does NOT give program times or even ranges, which is a rather a sly move on the part of Bosch. One rather irritating, if minor,  point is the inability of the window seal to drain completely, leaving about a tablespoon of water sitting in the bottom.  Bosch warn users to dry this &, for long life of the seal, that will be essential.\n",
      "\n",
      "평점 :  4\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2022-05-19\n",
      "\n",
      "제목 :  A lot of long washes.\n",
      "\n",
      "리뷰 내용 :  This only has one short wash a mixed wash and the start touch pad some times doesn’t work just beeps and beeps. A lot to get use to but it looks nice and stylish.\n",
      "\n",
      "평점 :  4\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2022-03-14\n",
      "\n",
      "제목 :  Which program?\n",
      "\n",
      "리뷰 내용 :  Relatively easy to use but we have to keep checking the manual and search through the programs for the best Cycle, you have to press the temperature and spin buttons to check that it is correct for the clothes in the drum, we wish that these indications were automatically displayed when the program is selected without having to check them individually. Some programs only spin up to 800 and heat up to 30*. we tend to use the 1400 @ 40* most of the time due to workwear. We'll get used to it eventually.\n",
      "\n",
      "평점 :  5\n",
      "========================================================================================================================\n",
      "================================================================================\n",
      "리뷰 작성 날짜 :  2022-05-18\n",
      "\n",
      "제목 :  Brilliant!\n",
      "\n",
      "리뷰 내용 :  I’ve only just received this product and used it a few times but even on the quick wash the stains are removed, the clothes smell fresh and clean and it’s very easy to use. And it is sooooo quiet!! I had a Hotpoint previously which was very noisy in comparison.Also the duo who delivered and installed it were fabulous! They went above and beyond and were very kind and helpful!\n",
      "\n",
      "평점 :  5\n",
      "========================================================================================================================\n"
     ]
    }
   ],
   "source": [
    "while True:\n",
    "    input_var = input('''\n",
    "\n",
    "번호를 입력하세요.\n",
    "\n",
    "1. WAN282X1GB Manual Keyword Frequency\n",
    "2. WAN282X1GB Manual Contents Keyword Set Review or Score\n",
    "3. WAN282X1GB Amazon Review Keyword Frequency\n",
    "4. WAN282X1GB Amazon Review or Score\n",
    "5. WAN282X1GB Manual Image Extraction\n",
    "6. Exit\n",
    "\n",
    "''')\n",
    "    if input_var == '1':\n",
    "        input_page1 = int(input('조회할 데이터 개수를 입력하세요.(최대 60 개) : '))\n",
    "        print('=' * 80)\n",
    "        print(Manual_Keyword_Frequency(document).head(input_page1))\n",
    "        \n",
    "    elif input_var == '2':\n",
    "        contents, contents_len = contents_exteaction(document)\n",
    "        \n",
    "        input_contents_number = input(\"\"\"\n",
    "        1. Manual Contents Search(목차 리스트만 출력)\n",
    "        2. Manual Contents Review search(목차와 매칭되는 리뷰 검색)\n",
    "        \"\"\")\n",
    "        print()\n",
    "        \n",
    "        if input_contents_number == '1':\n",
    "            print(f\"총 {contents_len}개의 목차가 검색되었습니다.\")\n",
    "            print('=' * 80)\n",
    "            print(contents)\n",
    "            \n",
    "        elif input_contents_number == '2':\n",
    "            print('추출된 목차 키워드 중 검색 가능한 키워드 목록')\n",
    "            print(\"-\" * 80)\n",
    "            print(contents_review_search(document))\n",
    "            input_contents_rev_1 = input('조회할 키워드를 입력하세요. : ')\n",
    "            input_contents_rev_2 = input(\"\"\"\n",
    "        \n",
    "        1. 리뷰 검색\n",
    "        2. 평점 검색\n",
    "        \n",
    "        \"\"\")\n",
    "            \n",
    "            if input_contents_rev_2 == '1':\n",
    "                title, sentence, date, star, data_len = Review_All_Search(input_contents_rev_1)\n",
    "\n",
    "                while True:\n",
    "                    input_search_option_rv = int(input(f\"조회할 데이터 개수를 입력하세요.(최대 조회 가능 건수({data_len}건)) : \"))\n",
    "                    if (input_search_option_rv > data_len):\n",
    "                        print('최대 조회가능 횟수를 초과하였습니다. 다시 입력하세요. : ')\n",
    "                    else:\n",
    "                        break\n",
    "                        \n",
    "                print(\"-\" * 80); print(\"\\n\")\n",
    "                print(f\"조회한 {input_search_option_rv}건의 조회 결과입니다.\")\n",
    "\n",
    "                for i in range(0, input_search_option_rv):\n",
    "                    print(\"=\" * 80)\n",
    "                    print('리뷰 작성 날짜 : ', date[i]); print()\n",
    "                    print('제목 : ', title[i]); print()\n",
    "                    print('리뷰 내용 : ', sentence[i]); print()\n",
    "                    print('평점 : ', star[i])\n",
    "                    print(\"=\" * 120)\n",
    "\n",
    "            elif input_contents_rev_2 == '2':\n",
    "                Crwaling_data_score_vis(input_contents_rev_1)    \n",
    "                  \n",
    "            \n",
    "    elif input_var == '3':\n",
    "        input_page2 = int(input('조회할 데이터 개수를 입력하세요.(최대 60개) : '))\n",
    "        print(\"=\" * 80)\n",
    "        print(Crawling_Text_Data_Keyword_Frequecy(df).head(input_page2))\n",
    "        \n",
    "    elif input_var == '4':\n",
    "        input_data_num = int(input(f'조회할 데이터 개수를 입력하세요.(최대 조회 가능 건수 {len(Manual_Keyword_Search_Score(document))} 건) : '))\n",
    "        print(\"=\" * 120)\n",
    "        print(Manual_Keyword_Search_Score(document).head(input_data_num))\n",
    "        input_page3 = input('조회할 키워드를 입력하세요. : ')\n",
    "        input_page3_options = input(\"\"\"\n",
    "        \n",
    "        1. 리뷰 검색\n",
    "        2. 평점 검색\n",
    "        \n",
    "        \"\"\")\n",
    "        \n",
    "        if input_page3_options == '1':\n",
    "            title, sentence, date, star, data_len = Review_All_Search(input_page3)\n",
    "            \n",
    "            while True:\n",
    "                input_search_option = int(input(f\"조회할 데이터 개수를 입력하세요.(최대 조회 가능 건수({data_len}건)) : \"))\n",
    "                if (input_search_option > data_len):\n",
    "                    print('최대 조회가능 횟수를 초과하였습니다. 다시 입력하세요. : ')\n",
    "                else:\n",
    "                    break\n",
    "            \n",
    "            print(f\"조회한 {input_search_option}건의 조회 결과입니다.\")\n",
    "            print(\"-\" * 80); print(\"\\n\")\n",
    "\n",
    "            for i in range(0, input_search_option):\n",
    "                print(\"=\" * 80)\n",
    "                print('리뷰 작성 날짜 : ', date[i]); print()\n",
    "                print('제목 : ', title[i]); print()\n",
    "                print('리뷰 내용 : ', sentence[i]); print()\n",
    "                print('평점 : ', star[i])\n",
    "                print(\"=\" * 120)\n",
    "\n",
    "        elif input_page3_options == '2':\n",
    "            Crwaling_data_score_vis(input_page3)\n",
    "            \n",
    "    elif input_var == '5':\n",
    "        input_image_num_1 = input(\"\"\"\n",
    "        \n",
    "        1. 이미지 출력\n",
    "        2. 동시출현 키워드 빈도 확인\n",
    "        \n",
    "        \"\"\")\n",
    "        \n",
    "        if input_image_num_1 == '1':\n",
    "            while True:\n",
    "                input_image_num_2 = int(input(\"출력할 이미지 개수를 입력하세요.(최대 13개) : \"))\n",
    "                if (input_image_num_2 > 13):\n",
    "                    print('최대 조회가능 횟수를 초과하였습니다. 다시 입력하세요. : ')\n",
    "                else:\n",
    "                    break\n",
    "                    \n",
    "            for i in range(0, input_image_num_2):\n",
    "                img_color = Image.open(f'manual_{i}.png')\n",
    "                img_color = np.array(img_color)\n",
    "                plt.imshow(img_color)\n",
    "                plt.show()\n",
    "                print()\n",
    "                \n",
    "        elif input_image_num_1 == '2':\n",
    "            list_im, count_im = Image_compare_review() \n",
    "            \n",
    "            print()\n",
    "            print(f'이미지에서 추출된 텍스트 목록 : {list_im}')\n",
    "            print(\"=\" * 80)\n",
    "            \n",
    "            if count_im == 0:\n",
    "                print(\"매칭되는 리뷰가 존재하지 않습니다.\")\n",
    "            \n",
    "            else:\n",
    "                print(\"매칭되는 리뷰가 존재합니다.\")\n",
    "            \n",
    "                \n",
    "    elif input_var == '6':\n",
    "        break\n",
    "\n",
    "print(\"종료되었습니다.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7ba831e1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
